### ISSUE TITLE
Unable to publish results to pact broker when provider version is set to "latest"

### ISSUE THREAD

**Issue by frastel** [pact-foundation/pact-php#92]
I am unable to publish results to pact broker when I set provider version to "latest"

given
```
class UserProviderTest extends TestCase
{
    public function testProviderDoesNotBreakThings()
    {
        $config = new VerifierConfig();
        $config
            ->setProviderName('user') // Providers name to fetch.
            ->setProviderVersion('latest')
            ->setProviderBaseUrl(new Uri('...')) // URL of the Provider.
            ->setBrokerUri(new Uri('http://pact-broker')) // URL of the Pact Broker to publish results.
            ->setPublishResults(true) // Flag the verifier service to publish the results to the Pact Broker.
            ->setProcessTimeout(60)
            ->setProcessIdleTimeout(20);

        // Verify that all consumers of 'someProvider' are valid.
        $verifier = new Verifier($config);
        $verifier->verifyAll();

        // This will not be reached if the PACT verifier throws an error, otherwise it was successful.
        $this->assertTrue(true, 'Pact Verification has failed.');
    }
}
```
The pacts are correctly read from the pact broker `/pacts/provider/user/latest` and
the standalone verifier is called correctly as a `frontend -> user` pact is given.

```
'/code/vendor/pact-foundation/pact-php/src/PhpPact/Standalone/Installer/../../../../pact/bin/pact-provider-verifier' 'http://pact-broker/pacts/provider/user/consumer/frontend/version/1.0.0' '--provider-base-url=http://user' '--provider-app-version=latest' '--publish-verification-results'
```

But I receive this error
```
Version number 'latest' cannot be parsed to a version number. The expected format (unless this configuration has been overridden) is a semantic version. eg. 1.3.0 or 2.0.4.rc1"
```
I am lost here because I am not able to set the provider version to 1.0.0 as `/pacts/provider/user/1.0.0` does not exist on the provider.

Currently I am quite confused how I am able to expose a provider version to the pact broker. As far as I understood this is only possible after verification. But when I try to do a verification for the very first time on the broker I am again in the mentioned problem (only "latest" is able to start the verification). Did I understood something completely wrong or is this a bug?

Error details
```
out > * User data given user with #1 existsout > 
err > /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/provider/verification_results/publish.rb:106:in `publish_verification_results'err > : err > Error returned from verification results publication 400 {"errors"=>{"provider_version"=>["Version number 'latest' cannot be parsed to a version number. The expected format (unless this configuration has been overridden) is a semantic version. eg. 1.3.0 or 2.0.4.rc1"]}}err >  (err > Pact::Provider::VerificationResults::PublicationErrorerr > )
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/provider/verification_results/publish.rb:41:in `call'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/provider/verification_results/publish.rb:21:in `call'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/provider/verification_results/publish_all.rb:20:in `block in call'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/provider/verification_results/publish_all.rb:19:in `collect'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/provider/verification_results/publish_all.rb:19:in `call'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/provider/verification_results/publish_all.rb:10:in `call'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/provider/rspec/pact_broker_formatter.rb:28:in `close'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:201:in `block in notify'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:200:in `each'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:200:in `notify'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:235:in `close'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:188:in `close_after'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:166:in `finish'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:76:in `report'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/provider/pact_spec_runner.rb:89:in `run_specs'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/provider/pact_spec_runner.rb:35:in `run'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/cli/run_pact_verification.rb:60:in `run_with_pact_uri'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/cli/run_pact_verification.rb:48:in `run_specs'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/cli/run_pact_verification.rb:21:in `call'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-1.33.0/lib/pact/cli/run_pact_verification.rb:14:in `call'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.15.0/lib/pact/provider_verifier/app.rb:111:in `verify_pact'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.15.0/lib/pact/provider_verifier/app.rb:29:in `block in call'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.15.0/lib/pact/provider_verifier/app.rb:28:in `collect'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.15.0/lib/pact/provider_verifier/app.rb:28:in `call'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.15.0/lib/pact/provider_verifier/app.rb:22:in `call'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.15.0/lib/pact/provider_verifier/cli/verify.rb:27:in `verify'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.15.0/lib/pact/provider_verifier/cli/custom_thor.rb:17:in `start'
err > 	from /code/vendor/pact-foundation/pact-php/pact/lib/app/pact-provider-verifier.rb:33:in `<main>'
```

**Comment by bethesque** [comment]
"latest" is not a valid version number. You should use `1.0.0` (actually, you should use something that includes the git sha - see the docs below). The pacticipant version resource will be automatically created for you when the pact is published.

Please read 
* https://github.com/pact-foundation/pact_broker/wiki/Publishing-and-retrieving-pacts
* https://docs.pact.io/getting_started/versioning_in_the_pact_broker

Also, please update to the latest version of the broker, where the version are ordered by timestamp instead of semantically.

**Comment by frastel** [comment]
I am aware of the fact that "latest" is not a valid version number. This is quite obvious.
However I wonder, why "latest" is taken as [default value for the version in this lib](https://github.com/pact-foundation/pact-php/blob/master/src/PhpPact/Broker/Service/BrokerHttpClient.php#L67).
I wouldn't have tested something with "latest" when this would not be used in the pact-php itself.

**Comment by frastel** [comment]
To make things clear I think there is a bug.

The provider version is used in [BrokerHttpClient::getAllConsumerUrls](https://github.com/pact-foundation/pact-php/blob/master/src/PhpPact/Broker/Service/BrokerHttpClient.php#L67) where `latest`IS allowed and for the [standalone verifier](https://github.com/pact-foundation/pact-php/blob/master/src/PhpPact/Standalone/ProviderVerifier/Verifier.php#L61) for publishing the provider version after verification.
In the later one `latest` is not allowed as it is no valid version number.

How about to use in Verifier::verifyAll always latest for the BrokerHttpClient? In this way the configured Version would only be used for publishing to the broker.

**Comment by frastel** [comment]
I'll prepare a PR to make things clear!

**Comment by frastel** [comment]
@bethesque Thanks for confirming the bug.

I am already on an according PR and will hardcode the url now as all other urls are harcoded there too.
